:sourcesdir: ../../../../source

[[recipes__conventions__import]]
==== 管理引入

在本章节，我们解决正确使用 HTML 引入的问题。

我们看看下面这个例子，有两个组件，各包含一个 paper 按钮。按钮不会做什么事情，但是这个例子演示了关于引入文件的有趣细节。

[subs="none"]
++++

<link rel="import" href="html/src/recipes/convention/import/parent-button-component.html">

<div class="polymer-demo-container">
    <parent-button-component></parent-button-component>
</div>

++++

*源码*

.index.html
[source, html]
----
<html>
<head>
	<link rel="import" href="src/recipes/convention/import/parent-button-component.html">
	<script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
</head>
<body>
    <parent-button-component></parent-button-component>
</body>
</html>
----

.src/recipes/convention/import/parent-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/parent-button-component.html[]
----

.src/recipes/convention/import/child-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/child-button-component.html[]
----

可以看到，我们忘了在子组件引入按钮控件，但是这个例子还是能正常运行。

如果我们之后重构 `parent-button-component` 的时候，觉得简单的 HTML `<button/>` 就足够，并且想删除 `paper-button`，那会发生什么？看看下面的例子。

.src/recipes/convention/import/parent-simple-button-component.html
[source, html]
----
include::{sourcesdir}/polymer-build/src/recipes/convention/import/parent-simple-button-component.html[]
----

*Result*

[subs="none"]
++++
    <iframe
        height="50"
        class="polymer-iframe-container"
        src="html/src/recipes/convention/import/iframe/parent-simple-button-component-app.html">

    </iframe>
++++

所以，我们不知不觉中破坏了子组件。

只是个简单的例子，但是展示了重要的东西。在真实的应用中，有好几十个组件会互相引入。所以，`paper-button` 可能不会在直接子组件中使用，而是在某个曾曾曾孙组件中使用。在复杂的重构后，很可能不会注意到有某些东西被破坏了。当最终发现某些组件不能正常工作的时候，就很难找到原因了。

而且还可能有更复杂的情况。在我们的例子中，我们在父组件中引入了 `paper-button`，而没在子组件中引入。但是我们也可以反着来做：在子组件引入，但是不在父组件引入。这样就能正常工作了！显然，这样会更容被破坏。

所有这些的关键就是我们需要小心使用引入。推荐在每个自定义组件中引入所有需要的组件，如果将来删除了某些 HTML 代码，同时检查并删除冗余的引入。这样的话，所有组件都保证在其它组件删除或者重构的时候还能正常工作。

可以通过运行 `polymer lint` 命令来自动检查引入。如果需要使用，必须安装 https://www.polymer-project.org/2.0/docs/tools/polymer-cli[polymer-cli]。

还有些可以使用的其它惯例。比如，可以在一个根组件中引入所有的 paper 跟 iron 元素，之后在所有其它的地方都可以使用而不需要 import 语句。或者甚至可以在根组件中引入所有的组件，然后在代码的任何地方都不需要在引入了。需要根据团队的偏好选择适应的方案。不管这些惯例是好是坏，有总比没有好。

[TIP]
====
如果在生产环境之前为客户端打过包，这个问题完全存在于开发环境。生产环境和测试代码不会有 import 语句，因为只会有一个单一的 HTML 包含所有代码。
====

